# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import calculate_ndvi_range as calculate_ndvi_range
from ecoscope.platform.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.results import (
    create_map_v2_widget_single_view as create_map_v2_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_tile_layers as merge_tile_layers
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import (
    persist_geoarrow_for_pydeck as persist_geoarrow_for_pydeck,
)
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.results._pydeck import (
    create_geoarrow_polygon_layer as create_geoarrow_polygon_layer,
)
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import (
    any_keyed_iterables_are_skips as any_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import convert_crs as convert_crs
from ecoscope_workflows_ext_custom.tasks.io import create_ndvi_tile as create_ndvi_tile
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    gee_client = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_client") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    roi = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client_name, **(params.get("roi") or {}))
        .call()
    )

    split_roi_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_roi_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=roi, groupers=groupers, **(params.get("split_roi_groups") or {}))
        .call()
    )

    ndvi_method = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("ndvi_method")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("ndvi_method") or {}))
        .call()
    )

    calculate_ndvi = (
        task(calculate_ndvi_range)
        .validate()
        .set_task_instance_id("calculate_ndvi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            time_range=time_range,
            ndvi_method=ndvi_method,
            baseline_time_range=None,
            image_size=1000000000,
            **(params.get("calculate_ndvi") or {}),
        )
        .mapvalues(argnames=["roi"], argvalues=split_roi_groups)
    )

    persist_ndvi_data = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_ndvi_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="ndvi",
            **(params.get("persist_ndvi_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=calculate_ndvi)
    )

    draw_ndvi = (
        task(draw_historic_timeseries)
        .validate()
        .set_task_instance_id("draw_ndvi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            current_value_column="NDVI",
            current_value_title="NDVI",
            historic_min_column="min",
            historic_max_column="max",
            historic_mean_column="mean",
            historic_band_title="Historic Min-Max",
            historic_mean_title="Historic Mean",
            layout_style=None,
            upper_lower_band_style={
                "mode": "lines",
                "line": {"color": "rgba(144, 238, 144, 0.8)"},
                "fillcolor": "rgba(144, 238, 144, 0.3)",
            },
            historic_mean_style=None,
            current_value_style=None,
            time_column="img_date",
            **(params.get("draw_ndvi") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=calculate_ndvi)
    )

    persist_ndvi = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_ndvi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_ndvi") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_ndvi)
    )

    ndvi_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("ndvi_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="NDVI Trends", **(params.get("ndvi_chart_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_ndvi)
    )

    grouped_ndvi_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_ndvi_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(widgets=ndvi_chart_widget, **(params.get("grouped_ndvi_widget") or {}))
        .call()
    )

    ndvi_tile = (
        task(create_ndvi_tile)
        .validate()
        .set_task_instance_id("ndvi_tile")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_client,
            time_range=time_range,
            ndvi_method=ndvi_method,
            reducer="mean",
            palette=None,
            scale=500,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="ndvi_geotiff",
            **(params.get("ndvi_tile") or {}),
        )
        .mapvalues(argnames=["roi"], argvalues=split_roi_groups)
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    roi_crs = (
        task(convert_crs)
        .validate()
        .set_task_instance_id("roi_crs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(crs="EPSG:4326", **(params.get("roi_crs") or {}))
        .mapvalues(argnames=["df"], argvalues=split_roi_groups)
    )

    persist_roi_parquet = (
        task(persist_geoarrow_for_pydeck)
        .validate()
        .set_task_instance_id("persist_roi_parquet")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            **(params.get("persist_roi_parquet") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=roi_crs)
    )

    combine_roi_gdf_and_url = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("combine_roi_gdf_and_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[roi_crs, persist_roi_parquet],
            **(params.get("combine_roi_gdf_and_url") or {}),
        )
        .call()
    )

    roi_boundary_layer = (
        task(create_geoarrow_polygon_layer)
        .validate()
        .set_task_instance_id("roi_boundary_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_line_color": [0, 128, 0, 255],
                "get_line_width": 2,
                "opacity": 1.0,
                "stroked": True,
                "filled": False,
                "line_width_units": "pixels",
            },
            legend=None,
            zoom=False,
            tooltip_columns=None,
            **(params.get("roi_boundary_layer") or {}),
        )
        .mapvalues(
            argnames=["geodataframe", "data_url"], argvalues=combine_roi_gdf_and_url
        )
    )

    merged_tile_layers = (
        task(merge_tile_layers)
        .validate()
        .set_task_instance_id("merged_tile_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(base_layers=base_maps, **(params.get("merged_tile_layers") or {}))
        .mapvalues(argnames=["overlay"], argvalues=ndvi_tile)
    )

    ndvi_map_layers = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("ndvi_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[roi_boundary_layer, merged_tile_layers],
            **(params.get("ndvi_map_layers") or {}),
        )
        .call()
    )

    ndvi_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("ndvi_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static=False,
            title=None,
            legend_style=None,
            max_zoom=20,
            view_state=None,
            output_type="json",
            **(params.get("ndvi_map") or {}),
        )
        .mapvalues(argnames=["geo_layers", "tile_layers"], argvalues=ndvi_map_layers)
    )

    ndvi_map_widget = (
        task(create_map_v2_widget_single_view)
        .validate()
        .set_task_instance_id("ndvi_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="NDVI Map", **(params.get("ndvi_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=ndvi_map)
    )

    grouped_ndvi_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_ndvi_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=ndvi_map_widget, **(params.get("grouped_ndvi_map_widget") or {})
        )
        .call()
    )

    ndvi_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("ndvi_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[grouped_ndvi_widget, grouped_ndvi_map_widget],
            time_range=time_range,
            groupers=groupers,
            **(params.get("ndvi_dashboard") or {}),
        )
        .call()
    )

    return ndvi_dashboard
