# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

load_spatial_features_group = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="load_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups

calculate_ndvi_range = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="calculate_ndvi_range",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)

create_ndvi_tile = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="create_ndvi_tile",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    merge_tile_layers as merge_tile_layers,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    gee_client = (
        set_gee_connection.validate()
        .set_task_instance_id("gee_client")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("gee_client") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    roi = (
        load_spatial_features_group.validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("roi") or {}))
        .call()
    )

    split_roi_groups = (
        split_groups.validate()
        .set_task_instance_id("split_roi_groups")
        .handle_errors()
        .with_tracing()
        .partial(
            df=roi, groupers=groupers, **(params_dict.get("split_roi_groups") or {})
        )
        .call()
    )

    ndvi_method = (
        set_string_var.validate()
        .set_task_instance_id("ndvi_method")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("ndvi_method") or {}))
        .call()
    )

    calculate_ndvi = (
        calculate_ndvi_range.validate()
        .set_task_instance_id("calculate_ndvi")
        .handle_errors()
        .with_tracing()
        .partial(
            client=gee_client,
            time_range=time_range,
            ndvi_method=ndvi_method,
            baseline_time_range=None,
            image_size=1000000000,
            **(params_dict.get("calculate_ndvi") or {}),
        )
        .mapvalues(argnames=["roi"], argvalues=split_roi_groups)
    )

    persist_ndvi_data = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_ndvi_data")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="ndvi",
            **(params_dict.get("persist_ndvi_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=calculate_ndvi)
    )

    draw_ndvi = (
        draw_historic_timeseries.validate()
        .set_task_instance_id("draw_ndvi")
        .handle_errors()
        .with_tracing()
        .partial(
            current_value_column="NDVI",
            current_value_title="NDVI",
            historic_min_column="min",
            historic_max_column="max",
            historic_mean_column="mean",
            historic_band_title="Historic Min-Max",
            historic_mean_title="Historic Mean",
            layout_style=None,
            upper_lower_band_style={
                "mode": "lines",
                "line": {"color": "rgba(144, 238, 144, 0.8)"},
                "fillcolor": "rgba(144, 238, 144, 0.3)",
            },
            historic_mean_style=None,
            current_value_style=None,
            time_column="img_date",
            **(params_dict.get("draw_ndvi") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=calculate_ndvi)
    )

    persist_ndvi = (
        persist_text.validate()
        .set_task_instance_id("persist_ndvi")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_ndvi") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_ndvi)
    )

    ndvi_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("ndvi_chart_widget")
        .handle_errors()
        .with_tracing()
        .partial(title="NDVI Trends", **(params_dict.get("ndvi_chart_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_ndvi)
    )

    grouped_ndvi_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_ndvi_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            widgets=ndvi_chart_widget, **(params_dict.get("grouped_ndvi_widget") or {})
        )
        .call()
    )

    ndvi_tile = (
        create_ndvi_tile.validate()
        .set_task_instance_id("ndvi_tile")
        .handle_errors()
        .with_tracing()
        .partial(
            client=gee_client,
            time_range=time_range,
            ndvi_method=ndvi_method,
            reducer="mean",
            palette=None,
            scale=500,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="ndvi_geotiff",
            **(params_dict.get("ndvi_tile") or {}),
        )
        .mapvalues(argnames=["roi"], argvalues=split_roi_groups)
    )

    base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("base_maps") or {}))
        .call()
    )

    roi_boundary_layer = (
        create_polygon_layer_pydeck.validate()
        .set_task_instance_id("roi_boundary_layer")
        .handle_errors()
        .with_tracing()
        .partial(
            layer_style={
                "get_line_color": [0, 128, 0, 255],
                "get_line_width": 2,
                "opacity": 1.0,
                "stroked": True,
                "filled": False,
                "line_width_units": "pixels",
            },
            legend=None,
            **(params_dict.get("roi_boundary_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_roi_groups)
    )

    merged_tile_layers = (
        merge_tile_layers.validate()
        .set_task_instance_id("merged_tile_layers")
        .handle_errors()
        .with_tracing()
        .partial(base_layers=base_maps, **(params_dict.get("merged_tile_layers") or {}))
        .mapvalues(argnames=["overlay"], argvalues=ndvi_tile)
    )

    ndvi_map_layers = (
        groupbykey.validate()
        .set_task_instance_id("ndvi_map_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            iterables=[roi_boundary_layer, merged_tile_layers],
            **(params_dict.get("ndvi_map_layers") or {}),
        )
        .call()
    )

    ndvi_map = (
        draw_map.validate()
        .set_task_instance_id("ndvi_map")
        .handle_errors()
        .with_tracing()
        .partial(
            static=False,
            title=None,
            legend_style=None,
            max_zoom=20,
            view_state=None,
            **(params_dict.get("ndvi_map") or {}),
        )
        .mapvalues(argnames=["geo_layers", "tile_layers"], argvalues=ndvi_map_layers)
    )

    persist_ndvi_map = (
        persist_text.validate()
        .set_task_instance_id("persist_ndvi_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_ndvi_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ndvi_map)
    )

    ndvi_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("ndvi_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(title="NDVI Map", **(params_dict.get("ndvi_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_ndvi_map)
    )

    grouped_ndvi_map_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_ndvi_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            widgets=ndvi_map_widget,
            **(params_dict.get("grouped_ndvi_map_widget") or {}),
        )
        .call()
    )

    ndvi_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("ndvi_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[grouped_ndvi_widget, grouped_ndvi_map_widget],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("ndvi_dashboard") or {}),
        )
        .call()
    )

    return ndvi_dashboard
