# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    create_ee_raster_tile_url as create_ee_raster_tile_url,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_feature_group as get_spatial_feature_group,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    calculate_ndvi_range as calculate_ndvi_range,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    gee_client = (
        set_gee_connection.validate()
        .set_task_instance_id("gee_client")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("gee_client") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    er_client = (
        set_er_connection.validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    roi = (
        get_spatial_feature_group.validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .partial(client=er_client, **(params_dict.get("roi") or {}))
        .call()
    )

    split_roi_groups = (
        split_groups.validate()
        .set_task_instance_id("split_roi_groups")
        .handle_errors()
        .with_tracing()
        .partial(
            df=roi, groupers=groupers, **(params_dict.get("split_roi_groups") or {})
        )
        .call()
    )

    calculate_ndvi = (
        calculate_ndvi_range.validate()
        .set_task_instance_id("calculate_ndvi")
        .handle_errors()
        .with_tracing()
        .partial(
            client=gee_client,
            time_range=time_range,
            baseline_time_range=None,
            **(params_dict.get("calculate_ndvi") or {}),
        )
        .mapvalues(argnames=["roi"], argvalues=split_roi_groups)
    )

    draw_ndvi = (
        draw_historic_timeseries.validate()
        .set_task_instance_id("draw_ndvi")
        .handle_errors()
        .with_tracing()
        .partial(
            current_value_column="NDVI",
            current_value_title="NDVI",
            historic_min_column="min",
            historic_max_column="max",
            historic_mean_column="mean",
            historic_band_title="Historic Min-Max",
            historic_mean_title="Historic Mean",
            layout_style=None,
            upper_lower_band_style=None,
            historic_mean_style=None,
            current_value_style=None,
            time_column="img_date",
            **(params_dict.get("draw_ndvi") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=calculate_ndvi)
    )

    persist_ndvi = (
        persist_text.validate()
        .set_task_instance_id("persist_ndvi")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_ndvi") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_ndvi)
    )

    ndvi_chart_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("ndvi_chart_widget")
        .handle_errors()
        .with_tracing()
        .partial(title="NDVI Trends", **(params_dict.get("ndvi_chart_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_ndvi)
    )

    grouped_ndvi_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_ndvi_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            widgets=ndvi_chart_widget, **(params_dict.get("grouped_ndvi_widget") or {})
        )
        .call()
    )

    base_maps = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("base_maps") or {}))
        .call()
    )

    ndvi_tile_url = (
        create_ee_raster_tile_url.validate()
        .set_task_instance_id("ndvi_tile_url")
        .handle_errors()
        .with_tracing()
        .partial(
            client=gee_client,
            time_range=time_range,
            image_collection="MODIS/061/MYD13A1",
            band="NDVI",
            reducer="mean",
            **(params_dict.get("ndvi_tile_url") or {}),
        )
        .mapvalues(argnames=["roi"], argvalues=split_roi_groups)
    )

    roi_boundary_layer = (
        create_polygon_layer_pydeck.validate()
        .set_task_instance_id("roi_boundary_layer")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("roi_boundary_layer") or {}))
        .mapvalues(argnames=["geodataframe"], argvalues=split_roi_groups)
    )

    ndvi_map_layers = (
        groupbykey.validate()
        .set_task_instance_id("ndvi_map_layers")
        .handle_errors()
        .with_tracing()
        .partial(
            iterables=[roi_boundary_layer, ndvi_tile_url],
            **(params_dict.get("ndvi_map_layers") or {}),
        )
        .call()
    )

    ndvi_map = (
        draw_map.validate()
        .set_task_instance_id("ndvi_map")
        .handle_errors()
        .with_tracing()
        .partial(tile_layers=base_maps, **(params_dict.get("ndvi_map") or {}))
        .mapvalues(
            argnames=["geo_layers", "overlay_tile_layers"], argvalues=ndvi_map_layers
        )
    )

    persist_ndvi_map = (
        persist_text.validate()
        .set_task_instance_id("persist_ndvi_map")
        .handle_errors()
        .with_tracing()
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_ndvi_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ndvi_map)
    )

    ndvi_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("ndvi_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(title="NDVI Map", **(params_dict.get("ndvi_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_ndvi_map)
    )

    grouped_ndvi_map_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_ndvi_map_widget")
        .handle_errors()
        .with_tracing()
        .partial(
            widgets=ndvi_map_widget,
            **(params_dict.get("grouped_ndvi_map_widget") or {}),
        )
        .call()
    )

    ndvi_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("ndvi_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[grouped_ndvi_widget, grouped_ndvi_map_widget],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("ndvi_dashboard") or {}),
        )
        .call()
    )

    return ndvi_dashboard
