# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_spatial_feature_group = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="get_spatial_feature_group",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups

calculate_ndvi_range = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="calculate_ndvi_range",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)

create_ee_raster_tile_url = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="create_ee_raster_tile_url",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "gee_client": [],
        "time_range": [],
        "er_client": [],
        "groupers": [],
        "roi": ["er_client"],
        "split_roi_groups": ["roi", "groupers"],
        "calculate_ndvi": ["gee_client", "time_range", "split_roi_groups"],
        "draw_ndvi": ["calculate_ndvi"],
        "persist_ndvi": ["draw_ndvi"],
        "ndvi_chart_widget": ["persist_ndvi"],
        "grouped_ndvi_widget": ["ndvi_chart_widget"],
        "base_maps": [],
        "ndvi_tile_url": ["gee_client", "time_range", "split_roi_groups"],
        "roi_boundary_layer": ["split_roi_groups"],
        "ndvi_map_layers": ["roi_boundary_layer", "ndvi_tile_url"],
        "ndvi_map": ["base_maps", "ndvi_map_layers"],
        "persist_ndvi_map": ["ndvi_map"],
        "ndvi_map_widget": ["persist_ndvi_map"],
        "grouped_ndvi_map_widget": ["ndvi_map_widget"],
        "ndvi_dashboard": [
            "workflow_details",
            "grouped_ndvi_widget",
            "grouped_ndvi_map_widget",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "gee_client": Node(
            async_task=set_gee_connection.validate()
            .set_task_instance_id("gee_client")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("gee_client") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "er_client": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("er_client") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "roi": Node(
            async_task=get_spatial_feature_group.validate()
            .set_task_instance_id("roi")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
            }
            | (params_dict.get("roi") or {}),
            method="call",
        ),
        "split_roi_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_roi_groups")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "df": DependsOn("roi"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_roi_groups") or {}),
            method="call",
        ),
        "calculate_ndvi": Node(
            async_task=calculate_ndvi_range.validate()
            .set_task_instance_id("calculate_ndvi")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
                "time_range": DependsOn("time_range"),
                "baseline_time_range": None,
            }
            | (params_dict.get("calculate_ndvi") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["roi"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "draw_ndvi": Node(
            async_task=draw_historic_timeseries.validate()
            .set_task_instance_id("draw_ndvi")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "current_value_column": "NDVI",
                "current_value_title": "NDVI",
                "historic_min_column": "min",
                "historic_max_column": "max",
                "historic_mean_column": "mean",
                "historic_band_title": "Historic Min-Max",
                "historic_mean_title": "Historic Mean",
                "layout_style": None,
                "upper_lower_band_style": None,
                "historic_mean_style": None,
                "current_value_style": None,
                "time_column": "img_date",
            }
            | (params_dict.get("draw_ndvi") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("calculate_ndvi"),
            },
        ),
        "persist_ndvi": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_ndvi")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_ndvi") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_ndvi"),
            },
        ),
        "ndvi_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("ndvi_chart_widget")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "title": "NDVI Trends",
            }
            | (params_dict.get("ndvi_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_ndvi"),
            },
        ),
        "grouped_ndvi_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_ndvi_widget")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("ndvi_chart_widget"),
            }
            | (params_dict.get("grouped_ndvi_widget") or {}),
            method="call",
        ),
        "base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_maps")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("base_maps") or {}),
            method="call",
        ),
        "ndvi_tile_url": Node(
            async_task=create_ee_raster_tile_url.validate()
            .set_task_instance_id("ndvi_tile_url")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_client"),
                "time_range": DependsOn("time_range"),
                "image_collection": "MODIS/061/MYD13A1",
                "band": "NDVI",
                "reducer": "mean",
            }
            | (params_dict.get("ndvi_tile_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["roi"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "roi_boundary_layer": Node(
            async_task=create_polygon_layer_pydeck.validate()
            .set_task_instance_id("roi_boundary_layer")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("roi_boundary_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "ndvi_map_layers": Node(
            async_task=groupbykey.validate()
            .set_task_instance_id("ndvi_map_layers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "iterables": [
                    DependsOn("roi_boundary_layer"),
                    DependsOn("ndvi_tile_url"),
                ],
            }
            | (params_dict.get("ndvi_map_layers") or {}),
            method="call",
        ),
        "ndvi_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("ndvi_map")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_maps"),
            }
            | (params_dict.get("ndvi_map") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "overlay_tile_layers"],
                "argvalues": DependsOn("ndvi_map_layers"),
            },
        ),
        "persist_ndvi_map": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_ndvi_map")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_ndvi_map") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("ndvi_map"),
            },
        ),
        "ndvi_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("ndvi_map_widget")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "title": "NDVI Map",
            }
            | (params_dict.get("ndvi_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_ndvi_map"),
            },
        ),
        "grouped_ndvi_map_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_ndvi_map_widget")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("ndvi_map_widget"),
            }
            | (params_dict.get("grouped_ndvi_map_widget") or {}),
            method="call",
        ),
        "ndvi_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("ndvi_dashboard")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("grouped_ndvi_widget"),
                    DependsOn("grouped_ndvi_map_widget"),
                ],
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("ndvi_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
