# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


import os
import sys
import traceback

from pydantic import BaseModel

from .params import Params
from .response import ResponseModel


def to_windows_safe_path(path: str):
    """
    Convert path to Windows extended-length format.
    Prevents module import failures in deeply nested folder structures
    """
    abs_path = os.path.abspath(path)
    return f"\\\\?\\{abs_path}"


def dispatch(
    execution_mode: str,  # TODO: literal type
    mock_io: bool,
    params: Params,
) -> ResponseModel:
    if sys.platform == "win32":
        sys.path = [to_windows_safe_path(p) for p in sys.path]
    match execution_mode, mock_io:
        case ("async", True):
            from .dags import run_async_mock_io

            dispatcher = run_async_mock_io
        case ("async", False):
            from .dags import run_async

            dispatcher = run_async
        case ("sequential", True):
            from .dags import run_sequential_mock_io

            dispatcher = run_sequential_mock_io
        case ("sequential", False):
            from .dags import run_sequential

            dispatcher = run_sequential
        case _:
            raise ValueError(f"Invalid execution mode: {execution_mode}")

    try:
        result: BaseModel = dispatcher(params=params)
        resp = {"result": result.model_dump()}
    except Exception as e:
        trace = traceback.format_exc()
        resp = {"error": str(e), "trace": trace}

    return ResponseModel(**resp)
