# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class Roi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str = Field(..., description="The path to ROI gpkg file", title="Url")
    roi_column: str | None = Field(
        "name", description="The column name of the ROI name", title="Roi Column"
    )
    roi_name: str | None = Field(None, description="The ROI name", title="Roi Name")
    layer_name: str | None = Field(
        None, description="The layer name", title="Layer Name"
    )


class CalculateNdvi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    band: str | None = Field("NDVI", description="The band name", title="Band")
    scale_factor: float | None = Field(
        0.0001, description="The scale factor", title="Scale Factor"
    )
    analysis_scale: float | None = Field(
        500.0, description="The analysis scale", title="Analysis Scale"
    )


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class TemporalGrouper(str, Enum):
    field_Y = "%Y"
    field_B = "%B"
    field_Y__m = "%Y-%m"
    field_j = "%j"
    field_d = "%d"
    field_A = "%A"
    field_H = "%H"
    field_Y__m__d = "%Y-%m-%d"


class ValueGrouper(str, Enum):
    name = "name"


class AxisStyle(BaseModel):
    title: str | None = Field(None, title="Title")
    range: list[float] | None = Field(None, title="Range")


class LayoutStyle(BaseModel):
    font_size: float | None = Field(None, title="Font Size")
    font_color: str | None = Field(None, title="Font Color")
    font_style: str | None = Field(None, title="Font Style")
    plot_bgcolor: str | None = Field(None, title="Plot Bgcolor")
    showlegend: bool | None = Field(None, title="Showlegend")
    hovermode: str | None = Field(None, title="Hovermode")
    legend_title: str | None = Field(None, title="Legend Title")
    title: str | None = Field(None, title="Title")
    title_x: float | None = Field(None, title="Title X")
    title_y: float | None = Field(None, title="Title Y")
    xaxis: AxisStyle | None = Field(None, title="Xaxis")
    yaxis: AxisStyle | None = Field(None, title="Yaxis")


class LineStyle(BaseModel):
    color: str | None = Field(None, title="Color")
    dash: str | None = Field(None, title="Dash")
    shape: str | None = Field(None, title="Shape")


class PlotStyle(BaseModel):
    xperiodalignment: str | None = Field(None, title="Xperiodalignment")
    marker_colors: list[str] | None = Field(None, title="Marker Colors")
    textinfo: str | None = Field(None, title="Textinfo")
    line: LineStyle | None = Field(None, title="Line")
    fillcolor: str | None = Field(None, title="Fillcolor")
    mode: str | None = Field(None, title="Mode")
    name: str | None = Field(None, title="Name")
    width: int | list[int] | None = Field(None, title="Width")
    xperiod: str | None = Field(None, title="Xperiod")


class GeeClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper | TemporalGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class DrawNdvi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    historic_band_title: str | None = Field(
        "Historic Min-Max",
        description="The title shown in the plot legend for historic band",
        title="Historic Band Title",
    )
    historic_mean_title: str | None = Field(
        "Historic Mean",
        description="The title shown in the plot legend for historic mean values",
        title="Historic Mean Title",
    )
    layout_style: LayoutStyle | None = Field(
        None,
        description="Additional kwargs passed to plotly.go.Figure(layout).",
        title="Layout Style",
    )
    upper_lower_band_style: PlotStyle | None = Field(
        None,
        description="Additional kwargs for upper_lower_band passed to plotly.graph_objects.Scatter.",
        title="Upper Lower Band Style",
    )
    historic_mean_style: PlotStyle | None = Field(
        None,
        description="Additional kwargs passed for historic_mean to plotly.graph_objects.Scatter.",
        title="Historic Mean Style",
    )
    current_value_style: PlotStyle | None = Field(
        None,
        description="Additional kwargs for current_value passed to plotly.graph_objects.Scatter.",
        title="Current Value Style",
    )
    time_column: str | None = Field(
        "img_date",
        description="The name of the dataframe column to pull historic max values from",
        title="Time Column",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    gee_client: GeeClient | None = Field(
        None, title="Select Google Earth Engine Data Source"
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    groupers: Groupers | None = Field(None, title="Set Groupers")
    roi: Roi | None = Field(None, title="Load ROI")
    calculate_ndvi: CalculateNdvi | None = Field(None, title="Calculate NDVI")
    draw_ndvi: DrawNdvi | None = Field(None, title="Draw NDVI")
