# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class NdviMethod(str, Enum):
    MODIS_MYD13A1_16_Day_Composite = "MODIS MYD13A1 16-Day Composite"
    MODIS_MCD43A4_Daily_NBAR = "MODIS MCD43A4 Daily NBAR"


class GroupingUnit(str, Enum):
    month = "month"
    week = "week"
    day_of_year = "day_of_year"
    modis_16_day = "modis_16_day"


class CalculateNdvi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    image_size: int | None = Field(
        1000000000,
        description="Number of historical satellite images to fetch. Set to a large value to retrieve all available historical data. Only used when baseline_time_range is not provided.",
        title="Image Size",
    )
    ndvi_method: NdviMethod | None = Field(
        "MODIS MYD13A1 16-Day Composite",
        description="Method to obtain NDVI values. 'MODIS MYD13A1 16-Day Composite': Uses pre-calculated NDVI from 16-day composites. Provides quality-filtered 'best pixel' values at 500m resolution with ~0.025 accuracy. Better for phenology studies but may saturate in dense canopies. 'MODIS MCD43A4 Daily NBAR': Uses daily nadir BRDF-adjusted reflectance. Computes NDVI from NIR/Red bands with view-angle correction for consistent measurements. Higher temporal resolution but more susceptible to cloud gaps.",
        title="Ndvi Method",
    )
    grouping_unit: GroupingUnit | None = Field(
        "month",
        description="Temporal unit for grouping historical data when calculating statistics. 'month': Compare against same calendar month (1-12). 'week': Compare against same ISO week number (1-53). 'day_of_year': Compare against same day of year (1-366). 'modis_16_day': Compare against same MODIS 16-day composite period (0-22).",
        title="Grouping Unit",
    )


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps1(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps6(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps7(BaseModel):
    url: (
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
        | None
    ) = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: int | None = Field(
        20,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: int | None = Field(
        0,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: (
        list[
            BaseMaps1
            | BaseMaps2
            | BaseMaps3
            | BaseMaps4
            | BaseMaps5
            | BaseMaps6
            | BaseMaps7
        ]
        | None
    ) = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
                "max_zoom": 20,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class Reducer(str, Enum):
    mean = "mean"
    median = "median"
    min = "min"
    max = "max"


class NdviTileUrl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ndvi_method: NdviMethod | None = Field(
        "precomputed",
        description="Method to obtain NDVI values. 'precomputed': Uses MODIS MYD13A1 16-day composite with pre-calculated NDVI. 'calculated': Uses MODIS MCD43A4 daily NBAR, computes NDVI from NIR/Red bands.",
        title="Ndvi Method",
    )
    reducer: Reducer | None = Field(
        "mean",
        description="Reducer to apply to the ImageCollection over the time range.",
        title="Reducer",
    )
    palette: list[str] | None = Field(
        None,
        description="Color palette for visualization, as hex color strings.",
        title="Palette",
    )
    scale: int | None = Field(
        500,
        description="Scale in meters for computing min/max statistics.",
        title="Scale",
    )


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalIndex(str, Enum):
    Year__example__2024_ = "%Y"
    Month__example__September_ = "%B"
    Year_and_Month__example__2023_01_ = "%Y-%m"
    Day_of_the_year_as_a_number__example__365_ = "%j"
    Day_of_the_month_as_a_number__example__31_ = "%d"
    Day_of_the_week__example__Sunday_ = "%A"
    Hour__24_hour_clock__as_number__example__22_ = "%H"
    Date__example__2025_01_31_ = "%Y-%m-%d"


class TemporalGrouper(BaseModel):
    temporal_index: TemporalIndex = Field(..., title="Time")


class IndexName(str, Enum):
    AOI_Name = "name"


class ValueGrouper(BaseModel):
    index_name: IndexName = Field(..., title="Category")


class Source(str, Enum):
    earthranger = "earthranger"


class EarthRangerSpatialFeatures(BaseModel):
    source: Literal["earthranger"] = Field("earthranger", title="Source")
    spatial_features_group_name: str = Field(
        ...,
        description="Name of the spatial features group in EarthRanger",
        title="Spatial Features Group Name",
    )


class Source1(str, Enum):
    local_file = "local_file"


class LocalFileSpatialFeatures(BaseModel):
    source: Literal["local_file"] = Field("local_file", title="Source")
    file_path: str = Field(
        ...,
        description="Local path to geoparquet or geopackage file",
        title="File Path",
    )
    layer: str | None = Field(
        None, description="Layer name (for geopackage files only)", title="Layer"
    )
    name_column: str | None = Field(
        "name", description="Column to use as region name", title="Name Column"
    )


class Source2(str, Enum):
    remote_file = "remote_file"


class RemoteFileSpatialFeatures(BaseModel):
    source: Literal["remote_file"] = Field("remote_file", title="Source")
    url: str = Field(
        ..., description="URL to download geoparquet or geopackage file", title="Url"
    )
    layer: str | None = Field(
        None, description="Layer name (for geopackage files only)", title="Layer"
    )
    name_column: str | None = Field(
        "name", description="Column to use as region name", title="Name Column"
    )


class Sort(str, Enum):
    ascending = "ascending"
    descending = "descending"


class LegendFromDataframe(BaseModel):
    title: str | None = Field("Legend", title="Title")
    label_column: str | None = Field("labels", title="Label Column")
    color_column: str | None = Field("colors", title="Color Column")
    sort: Sort | None = Field(None, title="Sort")
    label_suffix: str | None = Field(None, title="Label Suffix")


class LegendValue(BaseModel):
    label: str = Field(..., title="Label")
    color: str = Field(..., title="Color")


class Placement(str, Enum):
    top_left = "top-left"
    top_right = "top-right"
    bottom_left = "bottom-left"
    bottom_right = "bottom-right"
    fill = "fill"


class LegendStyle(BaseModel):
    placement: Placement | None = Field("bottom-right", title="Placement")


class ViewState(BaseModel):
    longitude: confloat(ge=-180.0, le=180.0) | None = Field(0, title="Longitude")
    latitude: confloat(ge=-90.0, le=90.0) | None = Field(0, title="Latitude")
    zoom: confloat(ge=0.0, le=20.0) | None = Field(0, title="Zoom")
    pitch: confloat(ge=0.0, le=60.0) | None = Field(0, title="Pitch")
    bearing: confloat(le=360.0) | None = Field(0, title="Bearing")


class GeeClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class ErClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[ValueGrouper] | None = Field(
        [{"index_name": "name"}],
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class Roi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config: (
        LocalFileSpatialFeatures
        | RemoteFileSpatialFeatures
        | EarthRangerSpatialFeatures
    ) = Field(
        ..., description="Configuration for spatial features source", title="Config"
    )


class NdviMap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    static: bool | None = Field(
        False, description="Set to true to disable map pan/zoom.", title="Static"
    )
    title: str | None = Field(
        None,
        description="            The map title. Note this is the title drawn on the map canvas itself, and will result\n            in duplicate titles if set in the context of a dashboard in which the iframe/widget\n            container also has a title set on it.\n            ",
        title="Title",
    )
    legend_style: LegendStyle | None = Field(
        None,
        description="Additional arguments for configuring the legend.",
        title="Legend Style",
    )
    max_zoom: int | None = Field(
        20,
        description="            The maximum zoom level allowed by the map.\n            This setting will be overridden if provided\n            tile layers max zoom levels are lower than this value.\n            ",
        title="Max Zoom",
    )
    view_state: ViewState | None = Field(
        None, description="Manually set the view state of the map.", title="View State"
    )


class LegendSegment(BaseModel):
    values: list[LegendValue] = Field(..., title="Values")
    title: str | None = Field("Legend", title="Title")


class RoiBoundaryLayer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    legend: LegendFromDataframe | LegendSegment | None = Field(
        None,
        description="If present, includes this layer in the map legend",
        title="Legend",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    gee_client: GeeClient | None = Field(
        None, title="Select Google Earth Engine Data Source"
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client: ErClient | None = Field(None, title="EarthRanger Data Source")
    groupers: Groupers | None = Field(None, title="Set Groupers")
    roi: Roi | None = Field(None, title="Load ROI")
    calculate_ndvi: CalculateNdvi | None = Field(None, title="Calculate NDVI")
    base_maps: BaseMaps | None = Field(None, title="Set Base Maps")
    ndvi_tile_url: NdviTileUrl | None = Field(None, title="Create NDVI Tile URL")
    roi_boundary_layer: RoiBoundaryLayer | None = Field(
        None, title="Create ROI Boundary Layer"
    )
    ndvi_map: NdviMap | None = Field(None, title="Draw NDVI Map")
