# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class NdviMethod(str, Enum):
    precomputed = "precomputed"
    calculated = "calculated"


class GroupingUnit(str, Enum):
    month = "month"
    week = "week"
    day_of_year = "day_of_year"


class CalculateNdvi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ndvi_method: Optional[NdviMethod] = Field(
        "precomputed",
        description="Method to obtain NDVI values. 'precomputed': Uses MODIS MYD13A1 16-day composite with pre-calculated NDVI. Provides quality-filtered 'best pixel' values at 500m resolution with ~0.025 accuracy. Better for phenology studies but may saturate in dense canopies. 'calculated': Uses MODIS MCD43A4 daily NBAR (nadir BRDF-adjusted reflectance). Computes NDVI from NIR/Red bands with view-angle correction for consistent measurements. Higher temporal resolution but more susceptible to cloud gaps.",
        title="Ndvi Method",
    )
    grouping_unit: Optional[GroupingUnit] = Field(
        "month",
        description="Temporal unit for grouping historical data when calculating statistics. 'month': Compare against same calendar month (1-12). 'week': Compare against same ISO week number (1-53). 'day_of_year': Compare against same day of year (1-366).",
        title="Grouping Unit",
    )


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class Source(str, Enum):
    earthranger = "earthranger"


class EarthRangerSpatialFeatures(BaseModel):
    source: Literal["earthranger"] = Field("earthranger", title="Source")
    spatial_features_group_name: str = Field(
        ...,
        description="Name of the spatial features group in EarthRanger",
        title="Spatial Features Group Name",
    )


class Source1(str, Enum):
    local_file = "local_file"


class LocalFileSpatialFeatures(BaseModel):
    source: Literal["local_file"] = Field("local_file", title="Source")
    file_path: str = Field(
        ...,
        description="Local path to geoparquet or geopackage file",
        title="File Path",
    )
    layer: Optional[str] = Field(
        None, description="Layer name (for geopackage files only)", title="Layer"
    )
    name_column: Optional[str] = Field(
        "name", description="Column to use as region name", title="Name Column"
    )


class Source2(str, Enum):
    remote_file = "remote_file"


class RemoteFileSpatialFeatures(BaseModel):
    source: Literal["remote_file"] = Field("remote_file", title="Source")
    url: str = Field(
        ..., description="URL to download geoparquet or geopackage file", title="Url"
    )
    layer: Optional[str] = Field(
        None, description="Layer name (for geopackage files only)", title="Layer"
    )
    name_column: Optional[str] = Field(
        "name", description="Column to use as region name", title="Name Column"
    )


class GeeClient(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class HistoricalTimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class Roi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config: Union[
        LocalFileSpatialFeatures, RemoteFileSpatialFeatures, EarthRangerSpatialFeatures
    ] = Field(
        ..., description="Configuration for spatial features source", title="Config"
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    gee_client: Optional[GeeClient] = Field(
        None, title="Select Google Earth Engine Data Source"
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    historical_time_range: Optional[HistoricalTimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Historical Time Range",
    )
    groupers: Optional[Groupers] = Field(None, title="Set Groupers")
    roi: Optional[Roi] = Field(None, title="Load ROI")
    calculate_ndvi: Optional[CalculateNdvi] = Field(None, title="Calculate NDVI")
