# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from ecoscope_workflows_core.tasks.results import DashboardJson, OutputFiles
from pydantic import BaseModel


class ResponseModel(BaseModel):
    result: DashboardJson | OutputFiles | None = None
    error: str | None = None
    trace: str | None = None
